### ISSUE TITLE
WebUI: Dashboard

### ISSUE THREAD

**Issue by tbkoay** [org-arl/r2c2#12]
In general, black needle indicates senator reading, red needle indicate target (command). 
- [x] Bearing. Black and red needle behaved like pitch and roll. Expect: red indicates target, black indicates sensor reading.
- [x] Pitch & Roll. The pitch and roll level indicator has half red and half black. Expect: Do a black horizontal line (for sensor reading) and a red horizontal line (for target).
- Most of the black needles do not move, is this due to the lack of sensor updates?

Priority: HIGH

**Comment by yashdeep97** [comment]
@tbkoay , yes the black needles do not move due to the lack of sensor updates, and some of them, for example LElevator, Rudder have not been handled yet..

**Comment by tbkoay** [comment]
- Bearing needle still need fixing
- Was having problem looking for a dashboard hidden behind other windows. Added a todo at the top.
