### ISSUE TITLE
[UI] Add mission planner

### ISSUE THREAD

**Issue by tbkoay** [org-arl/r2c2#13]
Add mission planner to the UI. This is in progress, add for completion.
- [x] Change the mission type
    - [x] clicking a highlighted missionPt allow one to change missionPt type
    - [x] double click on the point at the map shows a dropdown
- [x] Add delete mission points
- [x] Delete mission 
- [x] discard changes. Bug when 
- [x] save a mission (entire mission file?)
- [x] Drag point
- [x] click the missionPt at map highlights the missionPt in the mission panel

**Comment by tbkoay** [comment]
@yashdeep97 Just to clarify, when does the mission is uploaded to the vehicle?

**Comment by ngyewch** [comment]
#44 implements

> Delete mission
> Save mission

**Comment by ngyewch** [comment]
> clicking a highlighted missionPt allow one to change missionPt type

#44 This is done from the task view (right-hand side). Some changes were made as per the discussion we had earlier.

> double click on the point at the map shows a dropdown

I don't really see this as necessary. Left-clicking already selects the point and highlights it in the mission planner tree view (left-hand side), and the task view (right-hand side). Adding yet another dropdown will add more clutter. That said, what is the use case for this? What can the user do from this dropdown (if we add one)?

**Comment by ngyewch** [comment]
@yashdeep97 FYI #44 introduces very large changes for anything to do with MapComponent.

**Comment by ngyewch** [comment]
Closing this as #44 addresses most of this.

If any more related issues arise from #44, reopen this issue or open one or more new (more narrowly scoped) issues.
