### ISSUE TITLE
[UI] Add instruction to install WebUI and simulator

### ISSUE THREAD

**Issue by tbkoay** [org-arl/r2c2#3]
It would be useful for folks can play with the [WebUI](https://github.com/org-arl/r2c2/tree/copy-files-priv/experiments/WebUI) before providing you with more relevant feedback.

Please provide
- [x] Include reference to the technologies used for newbies
- [x] Simple installation guide
- [x] Where to get the simulator and installation process @ngyewch

**Comment by ngyewch** [comment]
I've updated the README in https://github.com/org-arl/r2c2/pull/5

The simulator can be downloaded from: https://github.com/org-arl/r2c2/releases/download/starfish-simulator-20200417-1230/starfish-simulator.zip
