### ISSUE TITLE
[UI] fea. Allow modification of geofence

### ISSUE THREAD

**Issue by tbkoay** [org-arl/r2c2#34]
Current state:

Click 'draw geofence' immediately clear existing geofence. One is to discard or safe.

Suggest:
- [x] Start with pre-existing geofence. Allow modification, add, insert, del, drag
- [x] Add a clear button to clear geofence
- [x] Can abort changes
- [x] Safe if satisfactory
- [x] Delete geofence point

**Comment by ngyewch** [comment]
Implemented in #44 
> Delete geofence point
